import type { LearntApplication } from '../../application'

export type LearntApplicationClient = Pick<
  LearntApplication,
  | 'getLearner'
  | 'getThemeMode'
  | 'setThemeMode'
  | 'getProductVocabularyMode'
  | 'setProductVocabularyMode'
  | 'hasCompletedFirstRunSetup'
  | 'completeFirstRunSetup'
  | 'listSubjects'
  | 'getSubjectOverview'
  | 'listSessions'
  | 'getLearningPackLibrary'
  | 'getInstalledLearningPacksForRuntime'
  | 'chooseAndInstallLearningPackDirectory'
  | 'syncSelectedLearningPackDirectory'
  | 'getLearningResource'
  | 'downloadLearningPackAsset'
  | 'listResourcesForPack'
  | 'listResourcesForConcept'
  | 'listResourcesForObjective'
  | 'listSupportResourcesForLearningItem'
  | 'listCurriculumEntries'
  | 'resolveStudySet'
  | 'startStudySetSession'
  | 'getAvailablePracticeScopes'
  | 'getSupportedPracticeModes'
  | 'createPracticeRequest'
  | 'createPracticePreset'
  | 'resolvePracticeCandidates'
  | 'createPracticePlan'
  | 'startPracticeSession'
  | 'getPracticeSummary'
  | 'getWeakConcepts'
  | 'getRecentMistakes'
  | 'getEligibleSupportResources'
  | 'recordResourceEngagement'
  | 'getSessionContext'
  | 'getSessionRecap'
  | 'getSessionConceptExploration'
  | 'startSession'
  | 'submitEvidence'
  | 'advanceSession'
  | 'changeInteractionMode'
  | 'abandonSession'
  | 'parkConcept'
  | 'unparkConcept'
>
