export const LearningPackErrorCode = {
  STRUCTURE_INVALID: 'STRUCTURE_INVALID',
  REQUIRED_FILE_MISSING: 'REQUIRED_FILE_MISSING',
  FILE_MANIFEST_MISMATCH: 'FILE_MANIFEST_MISMATCH',
  PACK_FILE_VERSION_MISMATCH: 'PACK_FILE_VERSION_MISMATCH',
  DUPLICATE_ID: 'DUPLICATE_ID',
  DUPLICATE_OPTION_ID: 'DUPLICATE_OPTION_ID',
  INVALID_ID: 'INVALID_ID',
  INVALID_PACK_ID: 'INVALID_PACK_ID',
  MISSING_REFERENCE: 'MISSING_REFERENCE',
  INVALID_CURRICULUM_PARENT: 'INVALID_CURRICULUM_PARENT',
  CURRICULUM_CYCLE: 'CURRICULUM_CYCLE',
  CONCEPT_PREREQUISITE_CYCLE: 'CONCEPT_PREREQUISITE_CYCLE',
  INVALID_ANSWER_OPTION_REFERENCE: 'INVALID_ANSWER_OPTION_REFERENCE',
  INVALID_RESPONSE_EVALUATION_PAIR: 'INVALID_RESPONSE_EVALUATION_PAIR',
  INVALID_PLAY_MODE_EVALUATOR: 'INVALID_PLAY_MODE_EVALUATOR',
  FLASHCARD_MISSING_SOLUTION: 'FLASHCARD_MISSING_SOLUTION',
  INVALID_MIGRATION_MAPPING: 'INVALID_MIGRATION_MAPPING',
  UNSUPPORTED_REQUIRED_CAPABILITY: 'UNSUPPORTED_REQUIRED_CAPABILITY',
  UNSUPPORTED_OPTIONAL_CAPABILITY: 'UNSUPPORTED_OPTIONAL_CAPABILITY',
  INVALID_ASSET_PATH: 'INVALID_ASSET_PATH',
  INVALID_CONTENT_BLOCK: 'INVALID_CONTENT_BLOCK',
  INVALID_THEME_ASSET_REFERENCE: 'INVALID_THEME_ASSET_REFERENCE',
  INVALID_RESOURCE_SOURCE: 'INVALID_RESOURCE_SOURCE',
  INVALID_RESOURCE_SEGMENT: 'INVALID_RESOURCE_SEGMENT',
  INVALID_RESOURCE_LINK: 'INVALID_RESOURCE_LINK',
  INVALID_RESOURCE_PROVENANCE: 'INVALID_RESOURCE_PROVENANCE',
  INVALID_CURRICULUM_ENTRY: 'INVALID_CURRICULUM_ENTRY',
  INVALID_URL: 'INVALID_URL',
  INVALID_RESOURCE_ENGAGEMENT_EVENT: 'INVALID_RESOURCE_ENGAGEMENT_EVENT',
} as const

export type LearningPackErrorCode =
  (typeof LearningPackErrorCode)[keyof typeof LearningPackErrorCode]

export type DiagnosticSeverity = 'error' | 'warning'

export interface LearningPackDiagnostic {
  code: LearningPackErrorCode
  severity: DiagnosticSeverity
  path: string
  message: string
}

export interface ValidationResult<T> {
  ok: boolean
  value?: T
  diagnostics: LearningPackDiagnostic[]
}

export function hasBlockingDiagnostics(
  diagnostics: readonly LearningPackDiagnostic[],
): boolean {
  return diagnostics.some((diagnostic) => diagnostic.severity === 'error')
}

export function makeDiagnostic(
  code: LearningPackErrorCode,
  severity: DiagnosticSeverity,
  path: string,
  message: string,
): LearningPackDiagnostic {
  return { code, severity, path, message }
}
